%YAML 1.2
---
networkDestination: /your/path
networkLocation: /your/path.t7
resultDestination: /your/path.csv
windowName: Metravision
redCrossEnabled: true
training:
    iterationCount: 1
    threashold: 0.60
network:
    imgWidth: 60
    imgHeight: 120 # Dimensions normalisées en entrée du réseau de neuronne.
window:
    height: 800
    width: 960
image:
    directoryLocation: /path/to/image-dataset
    nameFormat: "%06d.png"
    categories:
        bike:
            dirname: bike
            first: 1
            count: 1300
            learningFraction: [2, 3]  # 2 / 3
        notBike:
            dirname: not-bike
            first: 1
            count: 1800
            learningFraction: [2, 3]  # 2 / 3
video:
    directoryLocation: /path/to/videos
    short:
        directoryName: "short"
        files: !!set
            ? 8s.mp4
            ? bouchon-40s.mp4
            ? embouteillage-21s.mp4
            ? soleil-1m32.avi
            ? test-9s.avi
    medium:
        directoryName: "6min"
        files: !!set
            ? 1ereSequence.avi
            ? DerniereSequence.avi
            ? HeureDePointe.avi
    long: null