%YAML 1.2
---
configurationVersion: 1.1.3
printTimes: false
backgroundMode: false
developerMode: false
lecteur:
    randomJump: 0 # Between 0 and 1.
    segmentDuration: 6 # 6 # 60 # 360 # 3600 # seconds
    limitProcessingSpeedToRealVideoSpeed: never # always # auto
window:
    name: Metravision
    showCounts: true
    redCrossEnabled: true
    size:
        height: 960
        width: 800
    multiView:
        viewNumber: 14
        openEvent:
            click: false
            doubleClick: true
    progressBar:
        height: 30
        fgColor: [127, 192, 255]
        bgColor: [255, 255, 255]
processingTools:
    backgroundSubtractor:
        - type: MOG2
          shadowsAre: background # vehicles
          initArgs:
            history: 400
            varThreshold: 50
          runArgs:
            learningRate: 0.003
          set:
            backgroundRatio: 0.6
        - type: KNN
        - type: MOG
    erodeAndDilatePreBitwiseAnd:
        - erode: 4
        - dilate: 20
        - erode: 26
        - dilate: 15
    erodeAndDilatePostBitwiseAnd:
        - dilate: 4
    blobDetector:
        - parameters:
            minDistBetweenBlobs: 50
            filterByArea: True
            minArea: 1_500
            maxArea: 80_000
            filterByInertia: False # Inertia ~ Not elongated. [0, 1]
            minInertiaRatio: 0.1
            maxInertiaRatio: 1
            filterByCircularity: True # Perimeter/Area. [0, 1]
            minCircularity: 0
            maxCircularity: 0.96
            filterByConvexity: False # Area/Area of convex hull. [0, 1]
    tracking:
        - type: KCF
          frameCountTillDeath: 75 # It takes about 50 frames of traking usually
          trackingXminRatio: 0.35
          distanceCorrection:
            regionWidth: 400
            regionHeight: 400
            horizon: 0
            interpolation: INTER_LINEAR # INTER_CUBIC, INTER_LINEAR, INTER_NEAREST, INTER_AREA,
        - type: KCF
          frameCountTillDeath: 75 # ~3 seconds
          trackingXminRatio: 0.5
          countingLine: 0.95
        - type: TLD
          frameCountTillDeath: 300
          trackingXminRatio: 0.5
        - type: MEDIANFLOW
          frameCountTillDeath: 300
          trackingXminRatio: 0.5
        - type: GOTURN
          frameCountTillDeath: 300
          trackingXminRatio: 0.5
        - type: MOSSE
          frameCountTillDeath: 300
          trackingXminRatio: 0.5
    opticalFlow: false
    temporalDifferentiation: true
    contour: true
    ratioErode: 17 # How many pixels to subtract to each dimension before computing ratio
    ratioRef: 1.6 # Vehicles above this ratio (h/w) are detected as motos
resultDestinationTemplates:
    counts: "{video_directory}/mv-results/mv--{video_filename}.{ext}"

    example:
        counts: "{video_directory}/mv-results/mv--{mv_version}--year%Y-month%m-day%d-hour%H-minutes%m-seconds%s----{mv_date}--{video_filename}.{ext}"
    developer:
        counts: "/tmp/mv-results/mv--{mv_version}--{mv_date}--{video_filename}.{ext}"
    usableProperties:
        video_directory: The directory of the analysed video.
        video_filename: The name of the video file, without extension.
        video_extension: The extension of the video file.
        mv_date: The date of the day the result was compute, in local time.
        mv_datetime: Same as mv_date, but contains the hour as well.
        mv_utcdatetime: Same as mv_datetime, but in utc time.
        mv_version: The version of Metravision used to get the result. Mostly usefull for developers
        ext: The extension of the result file. Just leave it at the end of the template.
image:
    directoryLocation: /path/to/image-dataset
    nameTemplate: "%06d.png"
    categories:
        bike:
            dirname: bike
            first: 1
            count: 1300
            learningFraction: [2, 3]  # 2 / 3
        notBike:
            dirname: not-bike
            first: 1
            count: 1800
            learningFraction: [2, 3]  # 2 / 3
video:
    directoryLocation: /home/lox/Videos
    short:
        directoryName: "SequencesCourtes"
        files: !!set
            #? 8s.mp4
            #? bouchon-40s.mp4
            #? embouteillage-21s.mp4
            ? 6-motos--2016-10-26--11h35--brouillard.avi
            #? soleil-1m32.avi
            #? test-9s.avi
    medium: null
    mediu:
        directoryName: "Sequences6min"
        files: !!set
            #? 1ereSequence.avi
            ? DerniereSequence.avi
            #? HeureDePointe.avi
            #? SequenceDebut.avi
            #? SequenceFin.avi
            #? SequenceHeureDePointe.avi
    long: null
    l:
        directoryName: "SequencesLongues"
        files:
            #- 1h--2016-10-26--8h--nuit.avi
            #- 30m--2016-10-26--11h11--brouillard.avi
backgroundVideo:
    directoryLocation: /home/lox/Videos
    short: null
    medium:
        directoryName: "Sequences6min"
        files:
            - 1ereSequence.avi
            - DerniereSequence.avi
            #- HeureDePointe.avi
            - SequenceDebut.avi #- 08a.avi
            - SequenceFin.avi   #- 08b.avi
            #- SequenceHeureDePointe.avi
    long: null