%YAML 1.2
---
configurationVersion: 1.1.1
printTimes: true
backgroundMode: false
developerMode: true
lecteur:
    randomJump: 0
window:
    name: Metravision
    redCrossEnabled: true
    size:
        width: 960
        height: 800
    multiView:
        openEvent:
            click: false
            doubleClick: true
    progressBar:
        height: 30
        fgColor: [128, 255, 255]
        bgColor: [255, 255, 255]
processingTools:
    backgroundSubstractor:
        - type: MOG2
          shadowsAre: background # vehicles
        - type: KNN
        - type: MOG
    erodeAndDilatePreBitwiseAnd:
        - erode: 4
        - dilate: 20
        - erode: 26
        - dilate: 15
    erodeAndDilatePostBitwiseAnd:
        - dilate: 15
    blobDetector:
        - parameters:
            minDistBetweenBlobs: 4
            filterByArea: True
            minArea: 2_000
            maxArea: 20_000
            filterByInertia: True
            maxInertiaRatio: 3
    tracking:
        - type: KCF
          distanceCorrection:
            regionWidth: 400
            regionHeight: 400
          trackingXmin: 0.5
        - type: TLD
        - type: MEDIANFLOW
        - type: GOTURN
    opticalFlow: False
    contour: True
resultDestinationTemplates:
    counts: "{video_directory}/mv-results/mv--{video_filename}.{ext}"

    example:
        counts: "{video_directory}/mv-results/mv--{mv_version}--year%Y-month%m-day%d-hour%H-minutes%m-seconds%s----{mv_date}--{video_filename}.{ext}"
    developer:
        counts: "C:/pi/mv-results/mv--{mv_version}--{mv_date}--{video_filename}--{segmentIndex}.{ext}"
    usableProperties:
        video_directory: The directory of the analysed video.
        video_filename: The name of the video file, without extension.
        video_extension: The extension of the video file.
        mv_date: The date of the day the result was compute, in local time.
        mv_datetime: Same as mv_date, but contains the hour as well.
        mv_utcdatetime: Same as mv_datetime, but in utc time.
        mv_version: The version of Metravision used to get the result. Mostly usefull for developers
        ext: The extension of the result file. Just leave it at the end of the template.
        segmentIndex: |
            The index of the first and last segment that where treated.
            They are joined by a single hypens if all segments between them were treated as well (example 0-35).
            If they are joined by a double hypens (example 0--35), it means at least one segment is missing.
videoPerspectiveInformation:
    09.avi:
        xLeftEdge: 136
        xRightEdge: 743
        vanishingPoint: [548, 130]
image:
    directoryLocation: /path/to/image-dataset
    nameTemplate: "%06d.png"
    categories:
        bike:
            dirname: bike
            first: 1
            count: 1300
            learningFraction: [2, 3]  # 2 / 3
        notBike:
            dirname: not-bike
            first: 1
            count: 1800
            learningFraction: [2, 3]  # 2 / 3
video:
    directoryLocation: /path/to/videos
    short:
        directoryName: "SequencesCourtes"
        files: !!set
            ? 8s.mp4
            ? bouchon-40s.mp4
            ? embouteillage-21s.mp4
            ? soleil-1m32.avi
            ? test-9s.avi
    medium:
        directoryName: "Sequences6min"
        files: !!set
            ? 1ereSequence.avi
            ? DerniereSequence.avi
            ? HeureDePointe.avi
            ? SequenceDebut.avi #? 08a.avi
            ? SequenceFin.avi   #? 08b.avi
            ? SequenceHeureDePointe.avi
    long:
        directoryName: "SequencesLongues"
        files: !!set
            ? 01.avi
            ? 02.avi
            ? 03.avi
            ? 04.avi
            ? 05.avi
            ? 06.avi
            ? 07.avi
            ? 08.avi
            ? 09.avi
            ? 10.avi
            ? 11.avi
            ? demo-40min.avi
backgroundVideo:
    directoryLocation: /path/to/videos
    short: null
    medium:
        directoryName: "Sequences6min"
        files:
            - 1ereSequence.avi
            - DerniereSequence.avi
            #- HeureDePointe.avi
            - SequenceDebut.avi #? 08a.avi
            - SequenceFin.avi   #? 08b.avi
            #- SequenceHeureDePointe.avi
    long: null